# Generated by Django 3.2.9 on 2022-03-28 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now=True, null=True)),
                ('updatedAt', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('createdAt', models.DateTimeField(auto_now=True, null=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cric.user')),
            ],
        ),
        migrations.CreateModel(
            name='songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now=True, null=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('sungby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singer', to='cric.singer')),
                ('tags', models.ManyToManyField(blank=True, related_name='songs', to='cric.Tags')),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now=True, null=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cric.songs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cric.user')),
            ],
        ),
    ]
